/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as OauthAppsRouteImport } from './routes/oauth-apps'
import { Route as AuthErrorRouteImport } from './routes/auth-error'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users_.$userId'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations_.$orgId'
import { Route as AcceptInvitationInvitationIdRouteImport } from './routes/accept-invitation.$invitationId'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAppsRoute = OauthAppsRouteImport.update({
  id: '/oauth-apps',
  path: '/oauth-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth-error',
  path: '/auth-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/organizations_/$orgId',
  path: '/organizations/$orgId',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationInvitationIdRoute =
  AcceptInvitationInvitationIdRouteImport.update({
    id: '/accept-invitation/$invitationId',
    path: '/accept-invitation/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-error': typeof AuthErrorRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/organizations': typeof OrganizationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/users': typeof UsersRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-error': typeof AuthErrorRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/organizations': typeof OrganizationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/users': typeof UsersRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/audit-logs': typeof AuditLogsRoute
  '/auth-error': typeof AuthErrorRoute
  '/oauth-apps': typeof OauthAppsRoute
  '/organizations': typeof OrganizationsRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/users': typeof UsersRoute
  '/accept-invitation/$invitationId': typeof AcceptInvitationInvitationIdRoute
  '/organizations_/$orgId': typeof OrganizationsOrgIdRoute
  '/users_/$userId': typeof UsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/audit-logs'
    | '/auth-error'
    | '/oauth-apps'
    | '/organizations'
    | '/sessions'
    | '/settings'
    | '/sign-in'
    | '/users'
    | '/accept-invitation/$invitationId'
    | '/organizations/$orgId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/audit-logs'
    | '/auth-error'
    | '/oauth-apps'
    | '/organizations'
    | '/sessions'
    | '/settings'
    | '/sign-in'
    | '/users'
    | '/accept-invitation/$invitationId'
    | '/organizations/$orgId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/audit-logs'
    | '/auth-error'
    | '/oauth-apps'
    | '/organizations'
    | '/sessions'
    | '/settings'
    | '/sign-in'
    | '/users'
    | '/accept-invitation/$invitationId'
    | '/organizations_/$orgId'
    | '/users_/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  AuditLogsRoute: typeof AuditLogsRoute
  AuthErrorRoute: typeof AuthErrorRoute
  OauthAppsRoute: typeof OauthAppsRoute
  OrganizationsRoute: typeof OrganizationsRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  UsersRoute: typeof UsersRoute
  AcceptInvitationInvitationIdRoute: typeof AcceptInvitationInvitationIdRoute
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-apps': {
      id: '/oauth-apps'
      path: '/oauth-apps'
      fullPath: '/oauth-apps'
      preLoaderRoute: typeof OauthAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-error': {
      id: '/auth-error'
      path: '/auth-error'
      fullPath: '/auth-error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users_/$userId': {
      id: '/users_/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations_/$orgId': {
      id: '/organizations_/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$invitationId': {
      id: '/accept-invitation/$invitationId'
      path: '/accept-invitation/$invitationId'
      fullPath: '/accept-invitation/$invitationId'
      preLoaderRoute: typeof AcceptInvitationInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  AuditLogsRoute: AuditLogsRoute,
  AuthErrorRoute: AuthErrorRoute,
  OauthAppsRoute: OauthAppsRoute,
  OrganizationsRoute: OrganizationsRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  UsersRoute: UsersRoute,
  AcceptInvitationInvitationIdRoute: AcceptInvitationInvitationIdRoute,
  OrganizationsOrgIdRoute: OrganizationsOrgIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
