// Generated by `wrangler types` — do not hand-edit.
// Run `pnpm cf-typegen` to regenerate after changing wrangler.toml.
interface Env {
  // ── Cloudflare bindings ──────────────────────────────────────
  DB: D1Database;
  KV: KVNamespace;
  BUCKET: R2Bucket;

  // ── Runtime vars (wrangler.toml [vars] + secrets) ────────────
  AUTH_URL: string;
  BETTER_AUTH_SECRET: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  DISCORD_CLIENT_ID: string;
  DISCORD_CLIENT_SECRET: string;
  DASHBOARD_ADMIN_EMAIL: string;
}
