// Generated by `wrangler types` — do not hand-edit.
// Run `pnpm cf-typegen` to regenerate after changing wrangler.toml.
interface Env {
  // ── Cloudflare bindings ──────────────────────────────────────
  DB: D1Database;
  KV: KVNamespace;

  // ── Runtime vars (wrangler.toml [vars] + secrets) ────────────
  AUTH_URL: string;
  DASHBOARD_URL: string;
  BETTER_AUTH_SECRET: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  DISCORD_CLIENT_ID: string;
  DISCORD_CLIENT_SECRET: string;
  DASHBOARD_ADMIN_EMAIL: string;
  RESEND_API_KEY: string;
  // CDN integration
  CDN_URL: string;
  CDN_API_KEY: string;
}
